### ISSUE TITLE
Buffer deprecation warning

### ISSUE THREAD

**Issue by karlpokus** [substack/covert#15]
Hi!

I'm getting a deprecation warning on covert `1.1.0`.

> (node:34262) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by ljharb** [comment]
covert doesn't use `Buffer`; it's possible that v1.1.1 has addressed this by updating browserify.
